apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sample-app
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: sample-app
        env: {{ .Values.env }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      initContainers:
      - name: wait-for-db
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z db 3306; do
              echo "Waiting for MySQL..."
              sleep 2
            done

      # 🔽 ADD THIS INIT CONTAINER
      - name: django-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo "Running Django migrations..."
            cd /app/ecommerce
            python manage.py migrate --noinput
        envFrom:
        - configMapRef:
            name: sample-app-config
        - secretRef:
            name: sample-app-secret

      containers:
      - name: sample-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}

        envFrom:
        - configMapRef:
            name: sample-app-config
        - secretRef:
            name: sample-app-secret

        resources:
{{ toYaml .Values.resources | indent 10 }}
