# apiVersion: v1
# kind: Secret
# metadata:
#   name: sample-app-secret
#   namespace: {{ .Values.namespace }}
# type: Opaque
# stringData:
#   DB_PASSWORD: "password"


apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.SECRET_KEY | default "replace-me" | quote }}
