replicaCount: 1

image:
  repository: django-app
  pullPolicy: IfNotPresent
  tag: "v.133"

labels:
  app: django
  team: devops

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels:
  app: django
  team: devops

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000
httpRoute:
  enabled: false
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  hosts:
    - host: django.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - django.local
      secretName: django-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
