---
# Source: sample-app/templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_DATABASE: ecommerce_project
  MYSQL_USER: django_user
  MYSQL_PASSWORD: django_password
  MYSQL_ROOT_PASSWORD: root_password
---
# Source: sample-app/templates/secret.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: sample-app-secret
#   namespace: dev
# type: Opaque
# stringData:
#   DB_PASSWORD: "password"


apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secret
  namespace: dev
type: Opaque
stringData:
  SECRET_KEY: "replace-me"
---
# Source: sample-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: dev
data:
  ALLOWED_HOSTS: "sample.dev.local,localhost,127.0.0.1"
  DATABASE_URL: "mysql://django_user:django_password@db:3306/ecommerce_project"
  DEBUG: "True"
---
# Source: sample-app/templates/mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dev
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
# Source: sample-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: dev
spec:
  selector:
    app: sample-app
    env: dev
  ports:
  - port: 80
    targetPort: 8000
---
# Source: sample-app/templates/mysql-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: dev
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secret
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
# Source: sample-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sample.dev.local
    secretName: sample-dev-tls
  rules:
  - host: sample.dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-app
            port:
              number: 80
---
# Source: sample-app/templates/deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sample-app
#   namespace: dev
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sample-app
#       env: dev
#   template:
#     metadata:
#       labels:
#         app: sample-app
#         env: dev
#     spec:
#       serviceAccountName: dev-ci
#       containers:
#       - name: sample-app
#         image: "sample-app:latest"
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 8000

#         # 🔑 ADD THIS BLOCK ONLY
#         envFrom:
#         - configMapRef:
#             name: sample-app-config
#         - secretRef:
#             name: sample-app-secret

#         resources:
#           limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi



apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
      env: dev
  template:
    metadata:
      labels:
        app: sample-app
        env: dev
    spec:
      serviceAccountName: dev-ci

      initContainers:
      - name: wait-for-db
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z db 3306; do
              echo "Waiting for MySQL..."
              sleep 2
            done

      containers:
      - name: sample-app
        image: "sample-app:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

        envFrom:
        - configMapRef:
            name: sample-app-config
        - secretRef:
            name: sample-app-secret

        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
