env: staging
namespace: staging

django:
  DEBUG: "False"
  ALLOWED_HOSTS: "sample.staging.local"
  DATABASE_URL: "mysql://django_user:strong-password@db:3306/ecommerce_project"

host: sample.staging.local
tlsSecret: sample-staging-tls

httpRoute:
  enabled: false

