# replicaCount: 1

# containerPort: 8000

# service:
#   port: 80

# serviceAccount:
#   create: false
#   name: dev-ci

# resources:
#   requests:
#     cpu: 100m
#     memory: 128Mi
#   limits:
#     cpu: 250m
#     memory: 256Mi

# env:
#   django:
#     DEBUG: "True"
#     ALLOWED_HOSTS: "localhost,127.0.0.1"
#     DB_ENGINE: "django.db.backends.mysql"
#     DB_NAME: "ecommerce_project"
#     DB_HOST: "db"
#     DB_PORT: "3306"

# # --------------------
# # Secrets (empty here)
# # --------------------
# secrets: {}

# ingress:
#   enabled: true
#   className: nginx
#   annotations:
#     cert-manager.io/cluster-issuer: selfsigned-cluster-issuer

# # Added for httproute fix
# httpRoute:
#   enabled: false

replicaCount: 1
namespace: dev
env: dev

image:
  repository: sample-app
  tag: "0.3"
  pullPolicy: Never

containerPort: 8000

service:
  port: 80

serviceAccount:
  create: false
  name: dev-ci

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

django:
  DEBUG: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  DATABASE_URL: "mysql://django_user:django_password@db:3306/ecommerce_project"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer

host: sample.dev.local
tlsSecret: sample-dev-tls

httpRoute:
  enabled: false

mysql:
  enabled: true
  image: mysql:8.0
  database: ecommerce_project
  user: django_user
  password: django_password
  rootPassword: root_password
  storage: 5Gi
